### PR TITLE
Initial Setup

### PR DESCRIPTION
**Pull request by ritik307**
**Description**

- [x] Create routes 
- [x] Setup the homepage section
- [x] Setup the card section

### CODE REVIEW

**Comment by LordShenron** [comment]
have to be merged?

**Comment by ritik307** [comment]
@LordShenron yes! but the tags of gssoc21 and level are not showing my contribution on the gssoc site😟

**Comment by LordShenron** [comment]
> @LordShenron yes! but the tags of gssoc21 and level are not showing my contribution on the gssoc siteworried

It;s prolly a glitch.

**Comment by ritik307** [comment]
@LordShenron it's not a glitch I think you have to register the project somewhere to let `GSSOC` will get to know that this project is a part of it like you guys have done for the `wiki` and other projects.

**Comment by LordShenron** [comment]
> @LordShenron it's not a glitch I think you have to register the project somewhere to let `GSSOC` will get to know that this project is a part of it like you guys have done for the `wiki` and other projects.

okay then i think I who messed up here.. 

@ArunTeltia when doing a pull request to add this project to gssoc? DO IT ASAP MAN

**Comment by ArunTeltia** [comment]
Working on it

**Pull request merged**
